version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ./redis-data:/data
    networks:
      - webnet
  app:
    # COMPLETE HERE
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - webnet
networks:
  webnet:
