---
# OPTIONAL TASKS (needed to run checks from the host machine)
# - name: Uncomment the GitLab IP whitelist line
#   replace:
#     path: /etc/gitlab/gitlab.rb
#     regexp: '^# (gitlab_rails\[''monitoring_whitelist''\] = \[.*)\]$'
#     replace: '\1, ''20.20.20.1'']'

# - name: Reconfigure GitLab
#   command: gitlab-ctl reconfigure

# - name: Restart unicorn
#   command: gitlab-ctl restart unicorn
#   retries: 2
# END OF OPTIONAL TASKS

- name: Check redis --health
  uri:
    url: http://localhost:6379/health
    status_code: 200
    return_content: yes
  register: redis_health
  retries: 5
  delay: 10
  until: redis_health.status == 200
  tags: healthchecks

- name: Check redis --ping
  uri:
    url: http://localhost:6379/ping
    status_code: 200
    return_content: yes
  register: redis_ping
  retries: 5
  delay: 10
  until: redis_ping.status == 200
  tags: healthchecks