apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-v1
  labels:
    app: server-deployment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
      version: v1
  template:
    metadata:
      labels:
        app: server-deployment
        version: v1
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /srv/www
              name: redis-data
        - name: server
          image: ahddry/server-devops-blair-bon-2022
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-v2
  labels:
    app: server-deployment
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
      version: v2
  template:
    metadata:
      labels:
        app: server-deployment
        version: v2
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /srv/www
              name: redis-data
        - name: server
          image: ahddry/server-devops-blair-bon-2022
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
