#get server image from docker hub: https://hub.docker.com/repository/docker/ahddry/server-devops-blair-bon-2022 and run it with redis host and port
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment

spec:
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
        - name: server
          image: ahddry/server-devops-blair-bon-2022
          ports:
            - containerPort: 3000
        - name: redis
          image: redis:lastest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
              readOnly: false
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
