apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: node-redis
spec:
  ports:
    - name: server
      port: 3000
      targetPort: 3000
  type: NodePort
  selector:
    app: node-redis
