apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /srv/www
              name: redis-data
        - name: server
          image: ahddry/server-devops-blair-bon-2022
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
