apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: node-redis
spec:
  containers:
    - name: my-app
      image: ahddry/server-devops-blair-bon-2022
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: data
          mountPath: /www
          readOnly: false
      # data volume from where my-app read data those are written by redis
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
  volumes:
    - name: data
    hostPath:
      path: /data
      type: Directory
    # - name: data
      persistentVolumeClaim:
        claimName: redis-data